name: Build ever

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install DMD
        uses: dlang-community/setup-dlang@v2
        with:
          compiler: dmd-latest

      - name: Build with dub
        run: |
          dub build --build=release
          if [ -f "ever" ]; then
            echo "Build done."
          fi
