name: Build ever

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install DMD
        uses: dlang-community/setup-dlang@v2
        with:
          compiler: dmd-latest

      - name: Build with dub
        run: |
          cd cruntime
          make
          sudo mv libcbased.so /usr/local/lib
          cd ..
          cd src
          cd axiom
          dub || true
          sudo mv libaxiom.a /usr/local/lib
          cd runtime
          dub || true
          sudo mv libmarschiert.a /usr/local/lib
          cd ..
          dub build || true
          if [ -f "ever" ]; then
            echo "Build done."
          fi
      - name: Done
        run: |
          if [ -f "ever" ]; then
            echo "Build done."
          else
            echo "Error."
            exit 1
          fi
          
