name: Build ever
on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Test
        run: |
          sudo apt install dmd
          cd src
          dub
          if [ -f "ever" ]; then
            echo "Build Done."
          fi
